"""Mechanism tests for semantic column embeddings + cross-schema transfer.

These verify the properties that make schema transfer possible *without* heavy training:

  1. Frozen text embeddings of paraphrased column descriptions recover the cross-schema
     correspondence -- a sensor's nearest neighbour under the *other* schema's wording is
     its own match. This is the precondition for semantic transfer.
  2. An index embedder collapses every unseen column name to one shared [UNK] vector
     (the negative control: no cross-schema information), while the semantic encoder
     consumes a schema it was never given a vocabulary for.
  3. Cross-schema weight transfer moves the learned name->d_model projection (semantic)
     but leaves the untransferable column identities fresh (index).
  4. The text backbone stays frozen; only the projection (+ norm) trains.

The end-to-end Plant-A -> Plant-B RMSE comparison lives in scripts/schema_transfer.py.
"""

import os

import pandas as pd
import pytest
import torch


os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

from trea.models.column_embeddings import (  # noqa: E402
    IndexColumnEmbedder,
    SemanticColumnEmbedder,
    build_column_embedder,
)
from trea.models.single_row import TabularEncoder, TabularRegressor  # noqa: E402
from trea.training.single_row import copy_encoder_weights  # noqa: E402
from trea.utils.single_row_data import SingleRowConfig  # noqa: E402


# Same physical sensors, two schemas' wording (subset of the turbine glossary).
A_DESCR = {
    "AT": "ambient air temperature in degrees celsius",
    "TIT": "turbine inlet temperature in degrees celsius",
    "CDP": "compressor discharge pressure in millibar",
    "TEY": "turbine energy yield in megawatt hours",
}
B_DESCR_BY_A = {
    "AT": "outdoor intake air temperature, deg c",
    "TIT": "combustor outlet gas temperature entering the turbine, deg c",
    "CDP": "compressor outlet discharge pressure, mbar",
    "TEY": "net electrical power generated by the turbine, megawatt hours",
}
A_CODES = list(A_DESCR)
D = 16


@pytest.fixture(scope="module")
def semantic():
    """One MiniLM-backed embedder; the text backbone is shared across instances."""
    return SemanticColumnEmbedder(list(A_DESCR.values()), d_model=D)


def _cfg_and_df(codes, n=6):
    df = pd.DataFrame(
        {c: [0.1 * (i + j) for i in range(n)] for j, c in enumerate(codes)}
    )
    df["target"] = [float(i) for i in range(n)]
    return SingleRowConfig.generate(df, target="target"), df


def _num(df, codes):
    return torch.tensor(df[codes].values, dtype=torch.float32)


# --- 1. Semantic geometry recovers the cross-schema correspondence ---------------


def test_semantic_nn_recovers_correspondence(semantic):
    a = semantic._encode([A_DESCR[c] for c in A_CODES])
    b = semantic._encode([B_DESCR_BY_A[c] for c in A_CODES])
    sims = a @ b.T  # rows L2-normalized -> cosine
    nn = sims.argmax(dim=1)
    matched = (nn == torch.arange(len(A_CODES))).sum().item()
    # each A sensor's nearest B description should be its own paraphrase (allow one slip)
    assert matched >= len(A_CODES) - 1


def test_semantic_synonym_beats_unrelated(semantic):
    v = semantic._encode(
        [
            "ambient air temperature in degrees celsius",
            "outdoor intake air temperature, deg c",
            "number of open customer support tickets this week",
        ]
    )
    syn = (v[0] @ v[1]).item()
    unrelated = (v[0] @ v[2]).item()
    assert syn > unrelated + 0.2


# --- 2. Index = no cross-schema info; semantic consumes an unseen schema ----------


def test_index_embedder_unknown_name_collapses_to_unk():
    emb = IndexColumnEmbedder(["a", "b", "c"], d_model=D)
    seen = emb(["a"])
    unk1 = emb(["a column the vocab never saw"])
    unk2 = emb(["a different unseen column"])
    assert torch.allclose(unk1, unk2)  # every unseen name -> the one shared [UNK] row
    assert not torch.allclose(seen[0], unk1[0])


def test_semantic_encoder_consumes_unseen_schema(semantic):
    # Build a regressor on schema B's renamed codes whose descriptions the embedder
    # was never constructed with -> still finite (identity is name-derived, not indexed).
    codes = [f"tag_{i}" for i in range(len(A_CODES))]
    descr = {codes[i]: B_DESCR_BY_A[c] for i, c in enumerate(A_CODES)}
    cfg, df = _cfg_and_df(codes)
    emb = SemanticColumnEmbedder([descr[c] for c in codes], d_model=D)
    m = TabularRegressor(cfg, D, 2, 1, col_embedder=emb, column_descriptions=descr)
    assert torch.isfinite(m(_num(df, codes), None)).all()


# --- 3. Cross-schema weight transfer ---------------------------------------------


def _build_pair():
    cfgA, dfA = _cfg_and_df(A_CODES)
    codesB = [f"tag_{i}" for i in range(len(A_CODES))]
    descrB = {codesB[i]: B_DESCR_BY_A[c] for i, c in enumerate(A_CODES)}
    cfgB, dfB = _cfg_and_df(codesB)
    return cfgA, dfA, A_DESCR, cfgB, dfB, codesB, descrB


def test_semantic_transfer_moves_projection():
    torch.manual_seed(0)
    cfgA, dfA, descrA, cfgB, dfB, codesB, descrB = _build_pair()
    embA = SemanticColumnEmbedder([descrA[c] for c in A_CODES], d_model=D)
    embB = SemanticColumnEmbedder([descrB[c] for c in codesB], d_model=D)
    mA = TabularRegressor(cfgA, D, 2, 1, col_embedder=embA, column_descriptions=descrA)
    mB = TabularRegressor(cfgB, D, 2, 1, col_embedder=embB, column_descriptions=descrB)

    pA, pB = mA.tabular_encoder.col_embedder.proj, mB.tabular_encoder.col_embedder.proj
    with torch.no_grad():
        pA.weight.add_(1.0)  # make A's projection differ from B's init
    assert not torch.allclose(pA.weight, pB.weight)

    copy_encoder_weights(
        mA.tabular_encoder, mB.tabular_encoder, include_col_embedder=True
    )
    assert torch.allclose(pA.weight, pB.weight)  # projection transferred A -> B
    assert torch.isfinite(mB(_num(dfB, codesB), None)).all()


def test_index_transfer_leaves_identities_fresh():
    cfgA, dfA, descrA, cfgB, dfB, codesB, descrB = _build_pair()
    embA = IndexColumnEmbedder([descrA[c] for c in A_CODES], d_model=D)
    embB = IndexColumnEmbedder([descrB[c] for c in codesB], d_model=D)
    mA = TabularRegressor(cfgA, D, 2, 1, col_embedder=embA, column_descriptions=descrA)
    mB = TabularRegressor(cfgB, D, 2, 1, col_embedder=embB, column_descriptions=descrB)
    before = embB.embeddings.weight.clone()
    copy_encoder_weights(
        mA.tabular_encoder, mB.tabular_encoder, include_col_embedder=False
    )
    assert torch.allclose(before, embB.embeddings.weight)  # identities not transferred
    assert torch.isfinite(mB(_num(dfB, codesB), None)).all()


# --- 4. Frozen text backbone; only projection trains -----------------------------


def test_frozen_text_only_projection_trains():
    emb = SemanticColumnEmbedder(["a turbine temperature sensor reading"], d_model=D)
    emb(["a turbine temperature sensor reading"]).sum().backward()
    assert (
        emb.proj.weight.grad is not None and torch.isfinite(emb.proj.weight.grad).all()
    )
    _, mdl = SemanticColumnEmbedder._shared_text[emb.model_name]
    assert all(p.grad is None for p in mdl.parameters())  # text backbone stays frozen
    trainable = sum(p.numel() for p in emb.parameters() if p.requires_grad)
    expected = sum(
        p.numel() for p in list(emb.proj.parameters()) + list(emb.norm.parameters())
    )
    assert trainable == expected


# --- factory + backward compatibility --------------------------------------------


def test_build_column_embedder_factory():
    assert isinstance(build_column_embedder("index", ["x"], D), IndexColumnEmbedder)
    assert isinstance(
        build_column_embedder("semantic", ["x"], D), SemanticColumnEmbedder
    )
    with pytest.raises(ValueError):
        build_column_embedder("bogus", ["x"], D)


def test_index_path_backward_compatible():
    cfg, df = _cfg_and_df(A_CODES)
    m = TabularRegressor(cfg, D, 2, 1)  # col_embedder=None -> original index behaviour
    assert m(_num(df, A_CODES), None).shape == (len(df), 1)


# --- permutation invariance (load-bearing for cross-schema transfer) --------------


def test_column_permutation_invariance(semantic):
    # The encoder has no positional term over the column axis: permuting a row's
    # columns (identity + value together) must not change the output. Cross-schema
    # transfer relies on this -- if a positional encoding is ever added this breaks.
    cfg, _ = _cfg_and_df(A_CODES)
    emb = SemanticColumnEmbedder([A_DESCR[c] for c in A_CODES], d_model=D)
    m = TabularRegressor(cfg, D, 4, 2, col_embedder=emb, column_descriptions=A_DESCR)
    m.eval()
    enc = m.tabular_encoder
    row = torch.tensor([[0.3, -1.1, 2.0, 0.7]])
    with torch.no_grad():
        out_a = m(row, None)
    perm = [2, 3, 0, 1]
    enc.col_texts = [enc.col_texts[i] for i in perm]
    enc.numeric_texts = [enc.numeric_texts[i] for i in perm]
    with torch.no_grad():
        out_b = m(row[:, perm], None)
    assert torch.allclose(out_a, out_b, atol=1e-5)


def test_zero_value_keeps_column_identity():
    # The failure mode of `value * embedding`: at value 0 the numeric token is the zero
    # vector, so column identity is lost. With `identity + proj([value, present])` a
    # value of 0 yields a NON-zero token whose identity still distinguishes columns.
    cfg, _ = _cfg_and_df(A_CODES)
    emb = SemanticColumnEmbedder([A_DESCR[c] for c in A_CODES], d_model=D)
    enc = TabularEncoder(cfg, D, 2, 1, col_embedder=emb, column_descriptions=A_DESCR)
    value_vec = enc.num_value_proj(torch.tensor([[0.0, 1.0]]))  # value 0, present
    ids = emb(enc.numeric_texts)
    assert value_vec.abs().sum() > 1e-6  # value 0 does not zero the token
    tok0, tok1 = ids[0] + value_vec[0], ids[1] + value_vec[0]
    assert not torch.allclose(tok0, tok1, atol=1e-4)  # identity preserved at value 0


def test_nan_and_inf_treated_as_missing(semantic):
    # Raw NaN / inf inputs are handled natively as missing (present=0) -> finite output,
    # and are equivalent to the -inf missing sentinel. No pre-conversion required.
    cfg, _ = _cfg_and_df(A_CODES)
    emb = SemanticColumnEmbedder([A_DESCR[c] for c in A_CODES], d_model=D)
    m = TabularRegressor(cfg, D, 2, 1, col_embedder=emb, column_descriptions=A_DESCR)
    m.eval()
    nan_row = torch.tensor([[0.3, float("nan"), 2.0, float("inf")]])
    inf_row = torch.tensor([[0.3, float("-inf"), 2.0, float("-inf")]])
    with torch.no_grad():
        out_nan, out_inf = m(nan_row, None), m(inf_row, None)
    assert torch.isfinite(out_nan).all()
    assert torch.allclose(out_nan, out_inf, atol=1e-6)  # NaN/inf == missing sentinel
